### ISSUE TITLE
Bug: Loading between server requests takes time

### ISSUE THREAD

**Issue by AlineTheAlien** [MI-390/mRides-app#26]
The loading between some requests to the server takes time. There should be some kind of immediate response to tell the user that it is processing. (Logging in for example)

**Comment by AlineTheAlien** [comment]
@limphilip @nim442 What do you guys think about this? We can put a message or a loading bar to let the user know that the app has not frozen!

**Comment by limphilip** [comment]
@AlineTheAlien Yes, I think some kind of loading indication is good enough. From the UI class we can see it as "feedback" for the user, just to let them know that their request is processing, nothing too fancy since we are limited in time with all the user stories already.

**Comment by AlineTheAlien** [comment]
Fixed with the addition of the splashscreen (to indicate loading during log in) by @NassimElSayed. Closing issue
