### ISSUE TITLE
Bug: Attributes in domain objects may be null and used as null, throwing exceptions

### ISSUE THREAD

**Issue by limphilip** [MI-390/mRides-app#28]
When the first name or last name is null, the user object may have a null string as its first name attribute, which will throw an exception when used by the activities. It should be empty string by default, same for the other attributes. The server should also return a default value instead of null.

**Comment by nim442** [comment]
I will add a null check on the server

**Comment by limphilip** [comment]
Cool! I will initialize the attributes to some default values on the client side in the constructors so that the values won't be null, since it is also possible that an object is created only from client side, and used before it is sent to the server. In such cases, it will again throw an exception. I believe it is good practice anyway to have it in the constructors.

**Comment by limphilip** [comment]
By adding the default values in the constructor, I will have to update the mappers for them to send particular attributes of the model objects rather than the whole object. For instance, a user has multiple kind of lists, but when creating a user, we do not want to send those lists to the server. In this case, it might not have not effect, but it might affect the results for Request object. Hence, the control of data sent to the server should be controlled through the mappers.

**Comment by nim442** [comment]
We can close this issue?

**Comment by AlineTheAlien** [comment]
@limphilip Can we close this issue?

**Comment by limphilip** [comment]
@AlineTheAlien @nim442 I just found one place that is still missing a null check from the app side, i will push shortly. Sorry for the delay

**Comment by limphilip** [comment]
The only known problem remaining has been merged, closing this issue.
