### ISSUE TITLE
Bug : Application crashes when MapActivity tries to access empty user from a request

### ISSUE THREAD

**Issue by NassimElSayed** [MI-390/mRides-app#54]
It happens when you click on the destination marker on the map

**Comment by AlineTheAlien** [comment]
Hey @NassimElSayed , what do you mean by "empty user"? You want to catch the exception in our app?

**Comment by NassimElSayed** [comment]
@AlineTheAlien A user with null attributes. The source of this problem is the database, but I added a check so our application can catch it

**Comment by NassimElSayed** [comment]
Fixed in commit MI-101
