### ISSUE TITLE
Save account data at login so that the user wont have to relogin everytime

### ISSUE THREAD

**Issue by nim442** [MI-390/mRides-app#55]
Xamarin.auth has built in account manager therefore it should be trivial to implement this.

- On login, save account data by tag("facebook")
- Main activity check if already logged in
- On logout, delete fcmToken

**Comment by AlineTheAlien** [comment]
Should we add this to the next sprint?

**Comment by AlineTheAlien** [comment]
@NassimElSayed Could we close this issue since the pull request for this feature was recently merged?
