### ISSUE TITLE
Bug: Application crashes on phone when loading matches due to too many activities on UI thread

### ISSUE THREAD

**Issue by limphilip** [MI-390/mRides-app#80]
The app crashes when running it on mobile device (not emulator) on the matching screen. This is due to too many tasks happening on the UI thread, making it slow, so slow that the android OS considers it as unresponsive. In such situation, the android OS ends the application.

A solution _might_ be to convert those long tasks into `Async` tasks as shown on the following link: https://developer.android.com/reference/android/os/AsyncTask.html
This will allow the UI thread to be light, and the heavier tasks to be performed on independent threads. When finished, the `onPostExecute` method would run on the UI thread. (See link for more info).

The SAD should also be updated accordingly to include a `Task` package that the mapper would call.

**Comment by AlineTheAlien** [comment]
@limphilip Is this issue resolved?

**Comment by limphilip** [comment]
@AlineTheAlien Yes, thanks for reminding me! I'm closing it. I also updated the defect tracking document.
