### ISSUE TITLE
UI Refactoring: Color consistency across application

### ISSUE THREAD

**Issue by Ideawin** [MI-390/mRides-app#82]
If the user is a driver, the theme should be red while for a rider, the theme should be green. In some places, there is a mix of both colors so it must be fixed.

**Comment by AlineTheAlien** [comment]
@Ideawin Can we close this issue? The color consistency is great now 💯

**Comment by Ideawin** [comment]
Not yet, I'm going to check today! :)

**Comment by Ideawin** [comment]
The only thing remaining now is to make cancel ride activity page to adapt to rider/driver theme, which will be done soon, but overall everything is now consistent
